import type { Map as LeafletMap } from 'leaflet';
import type { BasemapPack } from '../../lib/basemapPack';
import type { BreadTrailPrefs, TrailPoint } from '../../lib/breadTrails';
import type { FieldIssue } from '../../lib/fieldStore';
import type { MapHighlightDoc } from '../../lib/mapHighlights';
import type { InfrastructurePin, OrchardBlock } from '../../lib/mapStore';
import type { OrchardMapDrawLayerCtx } from '../../lib/orchardMapDrawCreated';
import type { InternalBoundaryKind } from './BoundaryEditActionBar';
import type { MapMode, MapSubTab } from './editMapTypes';
import type { UserGeoFix } from './UserLocationLayer';

export type OrchardMapCanvasProps = {
  farmId: string;
  mapMode: MapMode;
  activeTab: MapSubTab;
  canEdit: boolean;
  viewport: { lat: number; lng: number; zoom: number };
  mapLayer: 'vector' | 'satellite';
  basemapPack: BasemapPack | null;
  showBasemapSetup: boolean;
  isOnline: boolean;
  useGoogleSatellite: boolean;
  googleMapsApiKey: string | undefined;
  onGoogleFail: () => void;
  onBasemapCancel: () => void;
  onBasemapComplete: () => Promise<void>;
  featureGroupRef: { current: any };
  drawLayerCtx: OrchardMapDrawLayerCtx;
  boundaryEditBlockId: string | null;
  showCoverage: boolean;
  pins: InfrastructurePin[];
  dailyEvents: Array<{
    id: string;
    blockId?: string;
    type: string;
    sprayType?: string;
    applicationMethod?: string;
    irrigationAmount?: number;
    notes?: string;
  }>;
  blockCenters: Record<string, [number, number]>;
  blocks: OrchardBlock[];
  fieldIssues: FieldIssue[];
  openIssuesByBlock: Record<string, number>;
  showIssueFlags: boolean;
  onSelectIssueBlock: (blockId: string) => void;
  onSelectIssue: (issue: FieldIssue) => void;
  mapHighlights: MapHighlightDoc[];
  canDeleteHighlight: (h: MapHighlightDoc) => boolean;
  onDeleteHighlight: (id: string) => void;
  userUid: string | undefined;
  userRole: string | undefined;
  crewSelfTrail: TrailPoint[];
  crewOthers: any[];
  trailPrefs: BreadTrailPrefs;
  reportDraft: { lat: number; lng: number; blockId?: string } | null;
  followUser: boolean;
  onUserFix: (fix: UserGeoFix | null) => void;
  mapTitle: string;
  onGoHome: () => void;
  onLocateMe: () => void;
  userFix: UserGeoFix | null;
  onToggleFlags: () => void;
  placingHighlight: boolean;
  highlightDraftGeo: GeoJSON.Feature | GeoJSON.Geometry | null;
  onToggleHighlight: () => void;
  placingFlag: boolean;
  onTogglePlaceFlag: () => void;
  onTrailPrefs: (next: BreadTrailPrefs) => void;
  selectedOperateBlock: OrchardBlock | null;
  highlightSending: boolean;
  onCancelHighlight: () => void;
  onSendHighlight: (payload: { note: string; durationSeconds: number }) => void;
  farmDefaultSeconds: number | undefined;
  chill: {
    portions: number | null;
    loading: boolean;
    error: string | null;
    stationName?: string;
    seasonLabel?: string;
  };
  onCloseBlock: () => void;
  onViewIssues: () => void;
  onReportIssue: (block: OrchardBlock) => void;
  issuesPanelBlock: OrchardBlock | null;
  issuesPanelOpen: boolean;
  issuesForPanel: FieldIssue[];
  reportBlockName?: string;
  selectedIssue: FieldIssue | null;
  onCloseIssues: () => void;
  onSelectIssueFly: (issue: FieldIssue) => void;
  onCancelReport: () => void;
  onSaveIssue: (data: {
    category: FieldIssue['category'];
    priority: FieldIssue['priority'];
    note: string;
  }) => Promise<void>;
  onCloseIssue: () => void;
  onResolveSelected: () => void;
  onResolveListedIssue: (issue: FieldIssue) => void;
  mapInstance: LeafletMap | null;
  onMapReady: (map: LeafletMap) => void;
  boundaryEditRef: { current: any };
  boundaryEditTick: number;
  onSaveBoundary: () => void;
  onDeleteBoundaryPoint: () => void;
  onCancelBoundary: () => void;
  onAddInternalBoundary?: (kind: InternalBoundaryKind) => void;
  internalBoundaryDrawing: { kind: InternalBoundaryKind; blockId: string } | null;
  onCancelDraw: () => void;
};
